// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    Breadcrumb: typeof import("./components/Breadcrumb/index.vue")["default"]
    DropdownMenu: typeof import("./components/DropdownMenu/index.vue")["default"]
    ErrorLog: typeof import("./components/ErrorLog/index.vue")["default"]
    GithubCorner: typeof import("./components/GithubCorner/index.vue")["default"]
    Hamburger: typeof import("./components/Hamburger/index.vue")["default"]
    HeaderSearch: typeof import("./components/HeaderSearch/index.vue")["default"]
    HelloWorld: typeof import("./components/HelloWorld.vue")["default"]
    Keyboard: typeof import("./components/Charts/Keyboard.vue")["default"]
    Mallki: typeof import("./components/TextHoverEffect/Mallki.vue")["default"]
    Pagination: typeof import("./components/Pagination/index.vue")["default"]
    PanThumb: typeof import("./components/PanThumb/index.vue")["default"]
    RightPanel: typeof import("./components/RightPanel/index.vue")["default"]
    Screenfull: typeof import("./components/Screenfull/index.vue")["default"]
    SizeSelect: typeof import("./components/SizeSelect/index.vue")["default"]
    SvgIcon: typeof import("./components/SvgIcon/index.vue")["default"]
    ThemePicker: typeof import("./components/ThemePicker/index.vue")["default"]
    Tinymce: typeof import("./components/Tinymce/index.vue")["default"]
    UploadExcel: typeof import("./components/UploadExcel/index.vue")["default"]
  }
}

export {}
